FROM python:3.7
WORKDIR /blog

COPY ./requirements.txt ./
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

COPY ./app/ ./app/
COPY ./docs/ ./docs/

RUN ls
RUN python3 app/app.py

# CMD [ "python3", "./app/app.py" ]