FROM node:10 as builder

LABEL maintainer = "me@kefan.me"

WORKDIR /blog
COPY package*.json ./
RUN npm install --no-optional
COPY src ./src
COPY public ./public
RUN npm run build

FROM nginx:1.19
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /blog/build /blog/build
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
