version: "3.7"

services:
  flask:
    build:
        context: .
        dockerfile: Dockerfile_flask
    container_name: flask
    expose:
      - 5000
    ports:
        - "5000:5000"

  nginx:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "3000:3000"
